# This is the configuration file for Azure Pipelines, used to run tests on
# macOS. Documentation to help understand this setup:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/index

trigger: none # disable builds for branches

jobs:
- job: macOS

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - checkout: self
    fetchDepth: 50
    submodules: false

  - script: |
      echo "Test jobs:"
      ./wpt test-jobs | while read job; do
        echo "$job"
        echo "##vso[task.setvariable variable=run_$job]true";
      done
    displayName: 'List test jobs'

  - script: |
      sudo easy_install pip
      pip install --user tox virtualenv
      echo "##vso[task.prependpath]$HOME/Library/Python/2.7/bin"
    displayName: 'Install Python packages'
    condition: |
      or(variables.run_tools_unittest,
         variables.run_wptrunner_unittest,
         variables.run_wpt_integration,
         variables.run_wptrunner_infrastructure)

  - script: tox -c tools/ -e py27 -- --junitxml=results.xml
    displayName: 'Run tools/ unittests'
    condition: variables.run_tools_unittest

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'tools/results.xml'
      testRunTitle: 'tools/ pytest'
    displayName: 'Publish tools/ unittests results'
    condition: variables.run_tools_unittest

  - script: tox -c tools/wptrunner/ -e py27-base,py27-safari -- --junitxml=results.xml
    displayName: 'Run tools/wptrunner/ unittests'
    condition: variables.run_wptrunner_unittest

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'tools/wptrunner/results.xml'
      testRunTitle: 'tools/wptrunner/ pytest'
    displayName: 'Publish tools/wptrunner/ unittests results'
    condition: variables.run_wptrunner_unittest

  - script: ./wpt make-hosts-file | sudo tee -a /etc/hosts
    displayName: 'Update /etc/hosts'
    condition: |
      or(variables.run_wpt_integration,
         variables.run_wptrunner_infrastructure)

  - template: tools/ci/install-browsers.yml
    parameters:
      chrome: $(run_wpt_integration)
      firefox: $(run_wpt_integration)

  - script: tox -c tools/wpt/ -e py27 -- --junitxml=results.xml
    displayName: 'Run tools/wpt/ tests'
    condition: variables.run_wpt_integration

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'tools/wpt/results.xml'
      testRunTitle: 'tools/wpt/ pytest'
    displayName: 'Publish tools/wpt/ test results'
    condition: variables.run_wpt_integration

  # Installig Ahem in /Library/Fonts instead of using --install-fonts is a
  # workaround for https://github.com/web-platform-tests/wpt/issues/13803.
  - script: sudo cp fonts/Ahem.ttf /Library/Fonts
    displayName: 'Install Ahem font'
    condition: variables.run_wptrunner_infrastructure

  - script: |
      # https://github.com/web-platform-tests/results-collection/blob/master/src/scripts/trust-root-ca.sh
      sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain tools/certs/cacert.pem
    displayName: 'Install web-platform.test certificate'
    condition: variables.run_wptrunner_infrastructure

  - template: tools/ci/install-browsers.yml
    parameters:
      safari: $(run_wptrunner_infrastructure)

  - script: ./wpt make-hosts-file | sudo tee -a /etc/hosts
    displayName: 'Update /etc/hosts'
    condition: variables.run_wptrunner_infrastructure

  - script: ./wpt manifest
    displayName: 'Update manifest'
    condition: variables.run_wptrunner_infrastructure

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=dev chrome infrastructure/
    displayName: 'Run infrastructure/ tests (Chrome Dev)'
    condition: variables.run_wptrunner_infrastructure

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=nightly firefox infrastructure/
    displayName: 'Run infrastructure/ tests (Firefox Nightly)'
    condition: variables.run_wptrunner_infrastructure

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=preview safari_webdriver infrastructure/
    displayName: 'Run infrastructure/ tests (Safari Technology Preview)'
    condition: variables.run_wptrunner_infrastructure
